[package]
name = "carve-html-import-worker"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
carve = { package = "carve-lang", git = "https://github.com/markup-carve/carve-rs", rev = "8a52398dd542d2d4f97f6ea2f83e6d8230df85e5" }
serde_json = "1"

[profile.release]
opt-level = 3
lto = true
